export const ROUTES = {
  // MAIN
  home: '/',
  student: '/student',
  tutor: '/tutor',
  teacher: '/teacher',
  forgot: '/forgot',
  reset: '/reset',
  signIn: '/sign-in',
  signUp: '/sign-up',
  singleCourse: '/courses/:id',
  findTeacher: '/find-teacher',
  payment: 'payment',
  createRoom: `createRoom`,
  room: `room/:roomId`,

  // STUDENT
  plan: 'plan',
  tutors: 'tutors',
  courses: 'courses',
  settings: 'settings',
  subscriptions: 'subscriptions',
  favorites: 'favorites',
  help: 'help',
  feedback: 'feedback',
  chat: 'chat',
  dashboard: 'dashboard',
  live: 'live',
  schedule: 'schedule',
  completed: 'completed',
  calendar: 'calendar',
  tutorId: 'tutorInfo/:id',

  // TUTOR
  priority: 'priority',
  library: 'library',
  history: 'history',
  incoming: 'incoming',
  unassigned: 'unassigned',
  upcoming: 'upcoming',
  reservation: 'reservations',
}
